#+TITLE: Emacs Configuration
#+OPTIONS: toc:nil num:nil

* General settings

** use-package
   Why does the default behaviour require you to write `:ensure t` for every single package. If I put it there I'm sure I want it!
#+BEGIN_SRC emacs-lisp
(require 'use-package-ensure)
(setq use-package-always-ensure t)
#+END_SRC

** startup screen
   none of these useless messages.
#+BEGIN_SRC emacs-lisp
(setq inhibit-startup-screen t)
(setq initial-scratch-message "") ;; Uh, I know what Scratch is for
#+END_SRC

** for graphical emacs
   remove all junk bars.
#+BEGIN_SRC emacs-lisp
(menu-bar-mode -1)
(tool-bar-mode -1)
(scroll-bar-mode 0)
#+END_SRC

** misc defaults
   emacs keeps asking wether to follow symlinks. can't see a reason why not to...
#+BEGIN_SRC emacs-lisp
(setq vc-follow-symlinks t)
#+END_SRC

    Matches parentheses and such in every mode
#+BEGIN_SRC emacs-lisp
(show-paren-mode 1)
#+END_SRC

    Stop creating backup~ files.
#+BEGIN_SRC emacs-lisp
(setq make-backup-files nil)
; stop creating #autosave# files
(setq auto-save-default nil)
#+END_SRC

save position of curser even after closing file.
#+BEGIN_SRC emacs-lisp
(save-place-mode t)
#+END_SRC
** strip trailing whitespace when saving
   nobody needs trailing whitespace.
#+BEGIN_SRC emacs-lisp
(add-hook 'before-save-hook 'delete-trailing-whitespace)
#+END_SRC

** tabs vs spaces
   use spaces instead of tabs. one tab should be two spaces if not specified otherwise.
#+BEGIN_SRC emacs-lisp
(setq-default indent-tabs-mode nil)
(setq tab-width 2)
#+END_SRC

** Answering just 'y' or 'n' will do
   ain't nobody got time to write entire words..
#+BEGIN_SRC emacs-lisp
(defalias 'yes-or-no-p 'y-or-n-p)
#+END_SRC

** emacs config
*** quick access
   configuring never stops. keep the config file close.
#+BEGIN_SRC emacs-lisp
(defun ab/visit-emacs-config ()
  (interactive)
  (find-file "~/.emacs.d/configuration.org"))

(global-set-key (kbd "C-c e") 'ab/visit-emacs-config)
#+END_SRC
*** reload
When regularly changing configs we also want to be able to use them without restarting emacs.
#+BEGIN_SRC emacs-lisp
(defun reload-init-file ()
  (interactive)
  (load-file user-init-file))

(global-set-key (kbd "C-c r") 'reload-init-file)
#+END_SRC

** persistent undo
such a handy feature!
#+BEGIN_SRC emacs-lisp
(global-undo-tree-mode)
(setq undo-tree-auto-save-history t)
(setq undo-tree-history-directory-alist '(("." . "~/.emacs.d/undo")))
#+END_SRC

** custom bindings
#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "M-o") 'other-window)
#+END_SRC
** TODO buffers
   find a good way to interact with buffers

#+BEGIN_SRC emacs-lisp
(setq ido-enable-flex-matching t)
(setq ido-everywhere t)
(ido-mode 1)
#+END_SRC
* Packages

** colors
#+BEGIN_SRC emacs-lisp
(use-package nord-theme)
(add-to-list 'custom-theme-load-path (expand-file-name "~/.emacs.d/themes/"))
(load-theme 'nord t)
#+END_SRC

** vi

no way around vi keybindings
#+BEGIN_SRC emacs-lisp
  (use-package evil
    :config
    (evil-mode 1))
#+END_SRC

*** TODO `evil-leader`
more vim functionality.
#+BEGIN_SRC emacs-lisp
(use-package evil-leader
  :config
  (global-evil-leader-mode)
  (evil-leader/set-leader " ")
  (evil-leader/set-key
    "b" 'switch-to-buffer
    "w" 'save-buffer))
#+END_SRC
this doesn't seem to work...

*** evil settings
evil for colemak keyboard layout
#+BEGIN_SRC emacs-lisp
; i needs to be unbound first
(define-key evil-normal-state-map "i" nil)

(define-key evil-motion-state-map "n" 'evil-next-line)
(define-key evil-motion-state-map "N" 'evil-join)
(define-key evil-motion-state-map "gn" 'evil-next-visual-line)
(define-key evil-motion-state-map "gN" 'evil-next-visual-line)
(define-key evil-motion-state-map "e" 'evil-previous-line)
(define-key evil-motion-state-map "ge" 'evil-previous-visual-line)
(define-key evil-motion-state-map "E" 'evil-lookup)
(define-key evil-motion-state-map "i" 'evil-forward-char)
(define-key evil-motion-state-map "j" 'evil-forward-word-end)
(define-key evil-motion-state-map "J" 'evil-forward-WORD-end)
(define-key evil-motion-state-map "gj" 'evil-backward-word-end)
(define-key evil-motion-state-map "gJ" 'evil-backward-WORD-end)
(define-key evil-motion-state-map "k" 'evil-search-next)
(define-key evil-motion-state-map "K" 'evil-search-previous)
(define-key evil-motion-state-map "gk" 'evil-next-match)
(define-key evil-motion-state-map "gK" 'evil-previous-match)
(define-key evil-motion-state-map "zi" 'evil-scroll-column-right)
(define-key evil-motion-state-map "zI" 'evil-scroll-right)
(define-key evil-motion-state-map "l" 'evil-insert)
(define-key evil-motion-state-map "L" 'evil-insert-line)

; `i` in visual mode needs extra remap
(define-key evil-visual-state-map "i" 'evil-next-visual-line)
#+END_SRC

** org mode

#+BEGIN_SRC emacs-lisp
(use-package org
  :init
  (setq org-hide-emphasis-markers t)
  :bind (("C-c l" . org-store-link)
         ("C-c a" . org-agenda)
         ("C-c c" . org-capture)))
#+END_SRC

*** fancy bullets
 fancy bullets in org mode
#+BEGIN_SRC emacs-lisp
  (use-package org-bullets
      :init
      :config
      (add-hook 'org-mode-hook (lambda () (org-bullets-mode 1))))
#+END_SRC

*** different font sizes for "headings"
    By default the only difference between org leves is a slightly different symbol (when using `org-bullets`) and an almost invisible indent.
    Different font sizes make much more sense.
#+BEGIN_SRC emacs-lisp
(custom-set-faces
  '(org-level-1 ((t (:inherit outline-1 :height 1.9))))
  '(org-level-2 ((t (:inherit outline-2 :height 1.5))))
  '(org-level-3 ((t (:inherit outline-3 :height 1.2))))
  '(org-level-4 ((t (:inherit outline-4 :height 1.0))))
  '(org-level-5 ((t (:inherit outline-5 :height 1.0))))
)
#+END_SRC

By default orgmode displays ellipsis for collapsed bullets. Here's a custom symbol indicating collapsed bullets.
#+BEGIN_SRC emacs-lisp
  (setq org-ellipsis " ...")
#+END_SRC
*** TODO evil org
    better keybindings for org in evil?

** pretty-mode
   Re-display parts of the Emacs buffer as pretty Unicode symbols.
#+BEGIN_SRC emacs-lisp
  ;; (use-package pretty-mode
  ;;   :ensure t)
  ;;   (global-pretty-mode t)
  ;;   (pretty-activate-groups
  ;;    '(:sub-and-superscripts :greek :arithmetic-nary))
#+END_SRC

emacs ships default with `prettify-symbols mode`.
#+BEGIN_SRC emacs-lisp
(global-prettify-symbols-mode 1)
#+END_SRC

** auto closing of parenthesis
does electric mode already provide this?
#+BEGIN_SRC emacs-lisp
(use-package smartparens
    :ensure t)

(smartparens-global-mode 1)
#+END_SRC

** commentary
gc comments stuff out
#+BEGIN_SRC emacs-lisp
(use-package evil-commentary
  :ensure t)
(evil-commentary-mode)
#+END_SRC

** LaTex
   which package to use? `tex-site` or `tex` ?
   is auctex itself a package?
#+BEGIN_SRC emacs-lisp
(use-package tex-site
  :ensure auctex
  :mode ("\\.tex\\'" . latex-mode)
  :config
  (setq TeX-auto-save t)
  (setq TeX-parse-self t)
  (setq-default TeX-master nil)
  (add-hook 'LaTeX-mode-hook
            (lambda ()
              (company-mode)
              (smartparens-mode)
              (turn-on-reftex)
              (setq reftex-plug-into-AUCTeX t)
              (reftex-isearch-minor-mode)
              (setq TeX-PDF-mode t)
              (setq TeX-source-correlate-method 'synctex)
              (setq TeX-source-correlate-start-server t)))

;; Update PDF buffers after successful LaTeX runs
(add-hook 'TeX-after-TeX-LaTeX-command-finished-hook
            #'TeX-revert-document-buffer)

;; to use pdfview with auctex
(setq TeX-view-program-selection '((output-pdf "Zathura"))
       TeX-source-correlate-start-server t)
(setq TeX-view-program-list '(("Zathura" "TeX-pdf-tools-sync-view"))))

(add-hook 'TeX-mode-hook 'prettify-symbols-mode)


; (use-package tex
;   :defer t
;   :ensure auctex
;   :config
;   (setq TeX-auto-save t))

#+END_SRC

** auto completion

#+BEGIN_SRC emacs-lisp
(use-package company
  :init
  (setq company-dabbrev-ignore-case t
        company-show-numbers t)
  (add-hook 'after-init-hook 'global-company-mode)
  :config
  (add-to-list 'company-backends 'company-math-symbols-unicode)
  :bind ("C-:" . company-complete)  ; In case I don't want to wait
  :diminish company-mode)
#+END_SRC

** snippets
#+BEGIN_SRC emacs-lisp
(use-package yasnippet
  :init
  (yas-global-mode 1))
  ; :config
  ; (add-to-list 'yas-snippet-dirs ("~/.emacs.d/snippets")))
#+END_SRC

** spell checking
# #+BEGIN_SRC emacs-lisp
# (use-package flyspell
#   :ensure t
#   :diminish flyspell-mode
#   :init
#   (add-hook 'prog-mode-hook 'flyspell-prog-mode)

#   (dolist (hook '(text-mode-hook org-mode-hook))
#     (add-hook hook (lambda () (flyspell-mode 1))))

#   (dolist (hook '(change-log-mode-hook log-edit-mode-hook org-agenda-mode-hook))
#     (add-hook hook (lambda () (flyspell-mode -1))))

#   :config
#   (setq ispell-program-name "/usr/bin/aspell"
#         ispell-local-dictionary "en_US"
#         ispell-dictionary "american" ; better for aspell
#         ispell-extra-args '("--sug-mode=ultra" "--lang=en_US")
#         ispell-list-command "--list"
#         ispell-local-dictionary-alist '(("en_US" "[[:alpha:]]" "[^[:alpha:]]" "['‘’]"
#                                       t ; Many other characters
#                                       ("-d" "en_US") nil utf-8))))
# (custom-set-variables
#  ;; custom-set-variables was added by Custom.
#  ;; If you edit it by hand, you could mess it up, so be careful.
#  ;; Your init file should contain only one such instance.
#  ;; If there is more than one, they won't work right.
#  '(package-selected-packages
#    (quote
#     (auctex yasnippet company use-package org-bullets evil-leader))))
# (custom-set-faces
#  ;; custom-set-faces was added by Custom.
#  ;; If you edit it by hand, you could mess it up, so be careful.
#  ;; Your init file should contain only one such instance.
#  ;; If there is more than one, they won't work right.
#  )
# #+END_SRC


#+BEGIN_SRC emacs-lisp



; (use-package pdf-tools
;   ; :ensure t
;   :pin manual ;; manually update
;  :config
;  ;; initialise
;  (pdf-tools-install)
;  ;; open pdfs scaled to fit page
;  (setq-default pdf-view-display-size 'fit-page)
;  ;; automatically annotate highlights
;  (setq pdf-annot-activate-created-annotations t)
;  ;; use normal isearch
;  (define-key pdf-view-mode-map (kbd "C-s") 'isearch-forward))
#+END_SRC
